# Generated by Django 4.2.6 on 2023-10-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocalizacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='images/')),
                ('image_name', models.TextField(max_length=100)),
                ('latitude', models.TextField(max_length=100)),
                ('longitude', models.TextField(max_length=100)),
                ('altitude', models.TextField(max_length=100)),
            ],
        ),
    ]
