# Generated by Django 4.1.5 on 2023-10-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_aps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocalizacao',
            name='image',
        ),
    ]
