# Generated by Django 4.1.5 on 2023-10-23 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_aps', '0004_geolocalizacao_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocalizacao',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='geolocalizacao',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='geolocalizacao',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='media/images/'),
        ),
    ]
